version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: my-redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  chess-server:
    image: chess-server:latest
    build:
      context: ./chess-server
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - JAVA_OPTS=-Xmx256m

volumes:
  redis-data:
